menu:
  Home: /
  Archive: /archives
  Links: /links
  About: /about

excerpt_link: 阅读全文 >

google_analytics: UA-5353535-6

rss: /atom.xml

comment_provider: duoshuo
# Duoshuo comment
duoshuo:
  short_name: jiabin